INSERT OR IGNORE INTO `categories` (`id`, `name`, `kind`) VALUES
	('income-salary', 'Salary', 'income'),
	('income-freelance', 'Freelance and side income', 'income'),
	('income-interest', 'Interest and dividends', 'income'),
	('income-refunds', 'Refunds', 'income'),
	('income-other', 'Other income', 'income'),
	('expense-housing', 'Housing', 'expense'),
	('expense-utilities', 'Utilities', 'expense'),
	('expense-groceries', 'Groceries', 'expense'),
	('expense-dining', 'Dining out', 'expense'),
	('expense-transport', 'Transport', 'expense'),
	('expense-health', 'Health', 'expense'),
	('expense-insurance', 'Insurance', 'expense'),
	('expense-communication', 'Communication', 'expense'),
	('expense-education', 'Education', 'expense'),
	('expense-leisure', 'Leisure', 'expense'),
	('expense-clothing', 'Clothing', 'expense'),
	('expense-personal-care', 'Personal care', 'expense'),
	('expense-gifts', 'Gifts and donations', 'expense'),
	('expense-taxes', 'Taxes and fees', 'expense'),
	('expense-other', 'Other expenses', 'expense');
